### PR TITLE
Add test for envoy example

### PR DESCRIPTION
**Pull request by lucianozablocki**
Solves #3 

Signed-off-by: Luciano <lucianozablocki@gmail.com>

### CODE REVIEW

**Review by marcosy — COMMENTED** [review]
Thanks @lucianozablocki! This is looking very good to me.

A thing that would be nice to do is to test that the connection does not succeed when it is expected to not succeed.

For example, as a final step in `test.sh`,  we could modify the web-server and echo-server entries to a SPIFFE ID different than the one Envoy expects. That should make the mTLS and TLS connection to fail respectively.

What do you think?

**Comment by lucianozablocki** [comment]
> Thanks @lucianozablocki! This is looking very good to me.
> 
> A thing that would be nice to do is to test that the connection does not succeed when it is expected to not succeed.
> 
> For example, as a final step in `test.sh`, we could modify the web-server and echo-server entries to a SPIFFE ID different than the one Envoy expects. That should make the mTLS and TLS connection to fail respectively.
> 
> What do you think?

Hi @marcosy, and thank you for the review!
You're right about that, I'll add a non-successful connection test also.

**Comment by marcosy** [comment]
Sure! That sounds good to me.

**Review by marcosy — APPROVED** [review]
LGTM!

**Pull request merged**
